.PHONY: clean All

All:
	@echo "----------Building project:[ hoard - Debug ]----------"
	@$(MAKE) -f  "hoard.mk"
clean:
	@echo "----------Cleaning project:[ hoard - Debug ]----------"
	@$(MAKE) -f  "hoard.mk" clean
